version: "3.7"
services:
  ProjectZomboidDedicatedServer:
    image: danixu86/project-zomboid-dedicated-server:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVERNAME=${SERVERNAME}
      - PASSWORD=${PASSWORD}
      - ADMINUSERNAME=${ADMINUSERNAME}
      - ADMINPASSWORD=${ADMINPASSWORD}
      - MODFOLDERS=${MODFOLDERS}
      - MEMORY=${MEMORY}
      - MOD_IDS=${MOD_IDS}
      - WORKSHOP_IDS=${WORKSHOP_IDS}
    ports:
      - "16261:16261/udp"
      - "16262:16262/udp"
      - "27015:27015/tcp"
    volumes:
      # Server data
      - ./data:/home/steam/Zomboid
      # Workshop mods folder
      - ./workshop-mods:/home/steam/pz-dedicated/steamapps/workshop
